import type { Metadata } from "next";
import "./globals.css";
// import "./embla-carousel.css";
import "./rtl.css";
import FooterNav from "../components/footer/footerNav";
import ReduxProvider from "../components/ReduxProvider";
import CartInitializer from "../components/cart/CartInitializer";
import WishlistInitializer from "../components/wishlist/WishlistInitializer";
import { Toaster } from "react-hot-toast";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getLocale } from 'next-intl/server';
import ThemeScript from "../components/ThemeScript";
import NavProgress from "../components/navProgress";
import LayoutWithMenuData from "../components/LayoutWithMenuData";
import ScriptLoader from "../components/ScriptLoader";
import ColorProvider from "../components/ColorProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  const isRTL = locale === 'ar';
  
  return (
    <html dir={isRTL ? 'rtl' : 'ltr'} lang={locale} suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body
        className={`bg-gray-50 text-base font-ltr rtl:font-rtl dark:text-white dark:bg-gray-900 min-h-screen flex flex-col ${isRTL ? 'font-rtl' : 'font-inter'}  ${isRTL ? 'rtl' : 'ltr'}`}
      >
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
            {/* <NetworkManager />
            <NetworkStatus showDetails={true} autoHide={true} hideDelay={5000} /> */}
            <div className="flex flex-col min-h-screen">
              <NavProgress />
              <CartInitializer />
              <WishlistInitializer />
              <LayoutWithMenuData>
              <ColorProvider>
                <main className="flex-1 pb-16 lg:pb-0">
                  {children}
                </main>
                </ColorProvider>
              </LayoutWithMenuData>
              <button className="te-footer-back-to-top back-to-top hidden lg:flex show" aria-label="Back to top">
                <svg className="te-footer-back-to-top-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="m5 9 7-7 7 7"></path>
                    <path d="M12 16V2"></path>
                    <circle cx="12" cy="21" r="1"></circle>
                </svg>
            </button>
            </div>
            <FooterNav />
          </ReduxProvider>
          <Toaster position="top-center" /> 
        </NextIntlClientProvider>
        <ScriptLoader />
      </body>
    </html>
  );
}
